server:
  servlet:
    context-path: /
  port: 9090

spring:
  application:
    name: gateway-3
  profiles:
    active:
      - default
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: Address-MSA
          uri: lb://ADDRESS-MSA
          predicates:
            - Path= /address-service/**
        - id: Student-MSA
          uri: lb://STUDENT-MSA
          predicates:
            - Path=/Student-service/**
            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true